title: "Star Wars: Forgotten Ones"
description: "A Star Wars Sage TTRPG Campaign"
url: "https://fo.galacticcampaigns.com"
baseurl: "" # Leave empty if using a custom domain, or set to /repo-name/

# Force Jekyll to include these folders
include:
  - assets
  - Chapter_Logs
  - Image_Resources

# This prevents Jekyll from ignoring files it doesn't recognize
keep_files:
  - assets
  - Chapter_Logs
  - Image_Resources
  - CNAME

# Markdown settings
markdown: kramdown
highlighter: rouge